services:
  - type: web
    name: contabot
    env: python
    plan: free
    region: frankfurt
    repo: https://github.com/xbeat/contabot
    branch: master
    autoDeploy: true        
    buildCommand: pip install -r requirements.txt
    startCommand: python contabot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GMAIL_CREDENTIALS_PATH
        value: /etc/secrets/credentials.json