services:
  - type: web
    name: contabot
    env: python
    plan: free
    region: frankfurt
    repo: https://github.com/xbeat/contabot
    branch: master
    autoDeploy: true        
    buildCommand: pip install -r requirements.txt
    startCommand: python contabot.py
    envVars:
      - key: ENV
        value: prod
      - key: DATABASE_URL
        sync: false  # URL del database Neon
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GOOGLE_API_KEY
        sync: false                